### ISSUE TITLE
Suppress warning, when using Svelte

### ISSUE THREAD

**Issue by huth-pesser** [ungap/global-this#10]
I use Apollo in a Svelte/Sapper project. Apollo has as dependency ts-invariant which has your lib as a dependency. 

On building my project I always get following warning

```
[rollup-plugin-svelte] The following packages did not export their `package.json` file so we could not check the "svelte" field. If you had difficulties importing svelte components from a package, then please contact the author and ask them to export the package.json file.

- @ungap/global-this
```

I suggest to change the exports tag of package.json file as follows to get rid of this warning:

```
  "exports": {
    ".": {
      "import": "./esm/index.js",
      "default": "./cjs/index.js"
    },
    "./*": "./"
  },
```

Could you please consider to change this in your sources?

**Comment by WebReflection** [comment]
did you mean to write the following?

```
  "exports": {
    ".": {
      "import": "./esm/index.js",
      "default": "./cjs/index.js"
    },
    "./package.json": "./package.json"
  },
```

I don't think `"./*": "./"` is a good idea in general

**Comment by huth-pesser** [comment]
Thanks for your fast response.

Your right, this is a better solution, because it solves the problem in a more specific way. 

It would be perfect if you could add this to your project. Thank you in advance.

**Comment by WebReflection** [comment]
PR welcome 👍

**Comment by WebReflection** [comment]
OK, this has been fixed 👋
