### ISSUE TITLE
打包后， global.globalThis = global; 后执行

### ISSUE THREAD

**Issue by uino-wuixn** [ungap/global-this#12]
![image](https://user-images.githubusercontent.com/73518894/143673925-2185e3c4-68ea-4ea0-ad27-0c98b2a2211a.png)

**Comment by uino-wuixn** [comment]
> ![image](https://user-images.githubusercontent.com/73518894/143673925-2185e3c4-68ea-4ea0-ad27-0c98b2a2211a.png)

导致global is undefined

**Comment by WebReflection** [comment]
polyfill goes **above code relying on polyfills** ... flip the dependencies around, import `globalThis` **first** and **then** the other module that needs *globalThis* to work.

**Comment by WebReflection** [comment]
P.S. to avoid *ReferenceError* you can use `if (typeof process === 'object')` instead of that *try/catch* ...

**Comment by uino-wuixn** [comment]
> P.S. to avoid _ReferenceError_ you can use `if (typeof process === 'object')` instead of that _try/catch_ ...

![image](https://user-images.githubusercontent.com/73518894/143678044-f897329c-7ff7-4010-b642-8d0b5de58b00.png)
![image](https://user-images.githubusercontent.com/73518894/143678059-e17ecb11-ebac-42f4-b091-975966102314.png)
代码是“rollup-plugin-inject-process-env”注入的

**Comment by WebReflection** [comment]
then file a bug to the rollup plugin, as there's **literally nothing I can do here**, it's not my code fault if you run my code after you need it 👋
