### ISSUE TITLE
ReferenceError: _T_ is not defined

### ISSUE THREAD

**Issue by wjw99830** [ungap/global-this#13]
This error occurred several times at production but can't be reproduced at development.
What's meaning of \_T\_ in this package? It seems like an undeclared variable.

**Comment by WebReflection** [comment]
that's exactly what it is, it's meant to trigger the `this` out of `window._T_` without needing to pass to window ... example:

```js
Object.defineProperty(Object.prototype, '_WUT_', { get() { console.log('Hello'); return 123 } });

_WUT_;
```

**Comment by wjw99830** [comment]
but why the error occurred? \_T\_ is defined by `Object.defineProperty` actually.

**Comment by WebReflection** [comment]
It’s defined as configurable accessor then deleted once accessed. I’ve no idea what error you’re talking about … maybe it’s one of your tools messing up the code and breaking it?

**Comment by wjw99830** [comment]
Maybe some browser don't support prototype query for globalThis?

**Comment by WebReflection** [comment]
it's not for globalThis, it's for `Object.prototype` ... I honestly don't know how to help you:

  * I've explained what the code does
  * I've tested this in every Mobile to Desktop browser
  * you can't tell me how to reproduce an error at all
  * I don't know which tool you are using in production

I can't do anything else unless you provide:

  * a way to reproduce any issue with this code
  * a reason for this code to fail under some circumstance
