### ISSUE TITLE
Add TypeSript Definitions

### ISSUE THREAD

**Issue by jonny-improbable** [ungap/global-this#3]
Thanks for providing this module, it would be awesome if typescript definitions could be provided.

**Comment by WebReflection** [comment]
As I don't use TS, I wouldn't know how to do that best. Any MR/help welcome, thanks

**Comment by jimmywarting** [comment]
Don't use TS either, go jsDoc!

for curiosity how do you add type definitions for something that could be either node, window, web worker or deno?

**Comment by WebReflection** [comment]
I wouldn't know how to write proper jsDoc neither, but I think defining it as `global` would be sufficient.

Although, I also think nobody really needs to know what `globalThis` is, as it's defined by specs, so I expect VS/Code to expose such info out of the blue

**Comment by ExE-Boss** [comment]
`globalThis`&nbsp;support requires&nbsp;**TypeScript 3.4**.

I’ve&nbsp;opened https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40712 to&nbsp;add&nbsp;correct type&nbsp;definitions, similar&nbsp;to&nbsp;what&nbsp;I&nbsp;did&nbsp;for&nbsp;https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40096.

**Comment by WebReflection** [comment]
Thanks. Closing this then, as that would solve it
