### ISSUE TITLE
`TypeError: undefined is not an object (evaluating this.globalThis = this)` on Safari 11 and below

### ISSUE THREAD

**Issue by ViktorShapoval** [ungap/global-this#7]
The error description is fully in the title.
Related to this code https://github.com/ungap/global-this/blob/master/index.js#L11

**Comment by WebReflection** [comment]
if you literally copy and paste that file in console, you'll have no errors, and `globalThis` available, so I guess you have an issue with your tools?

**Comment by ViktorShapoval** [comment]
@WebReflection You are right, thanks
The problem is that I'm using https://github.com/uNmAnNeR/imaskjs package, which uses global-this package, and in that scenario, it fails to work.

Anyway, I've used your superuseful ungap/degap and replaced imasks usage of global-this with core-js. Thanks for that degap
