### ISSUE TITLE
This is undefined in the iphone mobile browser

### ISSUE THREAD

**Issue by asins** [ungap/global-this#8]
In iPhone 7，iOS 12.1.4

![image](https://user-images.githubusercontent.com/898354/98243753-59b68500-1fa9-11eb-856c-bfe61a0bf216.png)

There 'this' is window ?

**Comment by asins** [comment]
I found that there is no this, but self exists

So improved：

```js
  function get() {
    const me = this || self;
    me.globalThis = me;
    delete Object.prototype._T_;
  }
```

**Comment by WebReflection** [comment]
how are you using this polyfill? is it as script tag? is it in a worker? this has been tested on iPhone too so this is new to me.

although, `self` might survive more cases, but please provide more details, thanks.

**Comment by asins** [comment]
I use this polyfill through import. It can be used normally after modifying the above code.
```js
import '@ungap/global-this';
```

The project is packaged using rollup's iife method, and the final JS file looks like this:
```js
var TEST_SDK = (function () {
  'use strict';

  (function (Object) {
    typeof globalThis !== 'object' && (
      this ?
        get() :
        (Object.defineProperty(Object.prototype, '_T_', {
          configurable: true,
          get: get
        }), _T_)
    );
    function get() {
      var me = this || self;
      me.globalThis = me;
      delete Object.prototype._T_;
    }
  }(Object));

 // do somthing
}());
```

**Comment by WebReflection** [comment]
this is a very weird behavior ... as if `this` is not there, accessing `_T_` should pass through the global context already, but I think a fallback for weird browsers makes sense.

One last question: is this running in a worker, or regular page?

**Comment by WebReflection** [comment]
P.S. it's been fixed, I just used `global` and published right away 👋

**Comment by asins** [comment]
> this is a very weird behavior ... as if `this` is not there, accessing `_T_` should pass through the global context already, but I think a fallback for weird browsers makes sense.
> 
> One last question: is this running in a worker, or regular page?

This is a regular page, not Worker page

**Comment by WebReflection** [comment]
Thanks for clarifying, the latest should be up "*and running*" 👍
